/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database connectivity */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current learner with top-bar stats */
        get: operations["get_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update learner preferences (daily goal) */
        patch: operations["update_me_api_users_me_patch"];
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List courses */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course detail with the learner's lesson count */
        get: operations["get_course_api_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learning path: units and skills with the learner's status */
        get: operations["get_path_api_courses__course_id__path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill with its lessons and their status */
        get: operations["get_skill_api_skills__skill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson exercises for play (never includes solutions) */
        get: operations["get_lesson_api_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a lesson attempt, or resume the active one
         * @description 201 when a new attempt is created, 200 when the in-progress attempt is resumed.
         */
        post: operations["start_attempt_api_lessons__lesson_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check one answer (idempotent per submission_id) */
        post: operations["check_answer_api_lessons__lesson_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** XP, daily goal, streak and course progress summary */
        get: operations["get_progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/lesson/{lesson_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a lesson attempt and receive rewards (idempotent) */
        post: operations["complete_lesson_api_progress_lesson__lesson_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hearts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hearts with regeneration info */
        get: operations["get_hearts_api_hearts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hearts/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refill hearts with gems */
        post: operations["refill_hearts_api_hearts_refill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This week's leaderboard */
        get: operations["get_leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile, stats and achievements */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AchievementMetric
         * @enum {string}
         */
        AchievementMetric: "lessons_completed" | "total_xp" | "longest_streak" | "skills_completed" | "perfect_lessons";
        /** AchievementSummaryOut */
        AchievementSummaryOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
        };
        /** AttemptOut */
        AttemptOut: {
            /** Attempt Id */
            attempt_id: string;
            /** Lesson Id */
            lesson_id: number;
            status: components["schemas"]["AttemptStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Solved Exercise Ids
             * @description Exercises already answered correctly.
             */
            solved_exercise_ids: number[];
            /** Mistakes */
            mistakes: number;
            /** Total Exercises */
            total_exercises: number;
            hearts: components["schemas"]["HeartsOut"];
        };
        /** AttemptProgressOut */
        AttemptProgressOut: {
            /** Solved Count */
            solved_count: number;
            /** Total Exercises */
            total_exercises: number;
            /** Mistakes */
            mistakes: number;
            /** Can Complete */
            can_complete: boolean;
        };
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "in_progress" | "completed";
        /** CheckAnswerIn */
        CheckAnswerIn: {
            /** Attempt Id */
            attempt_id: string;
            /** Exercise Id */
            exercise_id: number;
            /**
             * Submission Id
             * @description Client-generated id (e.g. UUID). Retrying with the same id is safe.
             */
            submission_id: string;
            /** Answer */
            answer: components["schemas"]["MultipleChoiceAnswer"] | components["schemas"]["WordBankAnswer"] | components["schemas"]["MatchPairsAnswer"] | components["schemas"]["FillBlankAnswer"] | components["schemas"]["TypeAnswerAnswer"];
        };
        /** CheckAnswerOut */
        CheckAnswerOut: {
            /** Submission Id */
            submission_id: string;
            /** Exercise Id */
            exercise_id: number;
            /** Is Correct */
            is_correct: boolean;
            /**
             * Correct Answer
             * @description Revealed only after the answer has been checked.
             */
            correct_answer: string;
            /**
             * Note
             * @description Soft feedback, e.g. an accent reminder.
             */
            note: string | null;
            /** Explanation */
            explanation: string | null;
            hearts: components["schemas"]["HeartsOut"];
            attempt: components["schemas"]["AttemptProgressOut"];
        };
        /** ChoiceOption */
        ChoiceOption: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Emoji */
            emoji?: string | null;
        };
        /** CompleteLessonIn */
        CompleteLessonIn: {
            /** Attempt Id */
            attempt_id: string;
        };
        /**
         * CompleteLessonOut
         * @description Result of a completion. Repeating the request returns the same body.
         */
        CompleteLessonOut: {
            /** Attempt Id */
            attempt_id: string;
            /** Lesson Id */
            lesson_id: number;
            /** First Completion */
            first_completion: boolean;
            /** Xp Awarded */
            xp_awarded: number;
            /** Xp Breakdown */
            xp_breakdown: components["schemas"]["XpAwardOut"][];
            /** Gems Awarded */
            gems_awarded: number;
            /** Mistakes */
            mistakes: number;
            /** Accuracy */
            accuracy: number;
            /** Total Xp */
            total_xp: number;
            /** Gems */
            gems: number;
            daily: components["schemas"]["DailyGoalOut"];
            streak: components["schemas"]["StreakOut"];
            hearts: components["schemas"]["HeartsOut"];
            skill_progress: components["schemas"]["SkillProgressOut"];
            /**
             * Unlocked Skill Id
             * @description Skill unlocked by this completion, if any.
             */
            unlocked_skill_id: number | null;
            /**
             * Next Lesson Id
             * @description Where the path continues.
             */
            next_lesson_id: number | null;
            /** New Achievements */
            new_achievements: components["schemas"]["AchievementSummaryOut"][];
        };
        /** CourseDetailOut */
        CourseDetailOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Learning Language */
            learning_language: string;
            /** From Language */
            from_language: string;
            /** Description */
            description: string | null;
            /** Unit Count */
            unit_count: number;
            /** Skill Count */
            skill_count: number;
            /** Lesson Count */
            lesson_count: number;
            /** Completed Lesson Count */
            completed_lesson_count: number;
        };
        /** CourseListOut */
        CourseListOut: {
            /** Courses */
            courses: components["schemas"]["CourseOut"][];
        };
        /** CourseOut */
        CourseOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Learning Language */
            learning_language: string;
            /** From Language */
            from_language: string;
            /** Description */
            description: string | null;
        };
        /** CourseProgressOut */
        CourseProgressOut: {
            /** Course Id */
            course_id: number;
            /** Lessons Completed */
            lessons_completed: number;
            /** Total Lessons */
            total_lessons: number;
            /** Skills Completed */
            skills_completed: number;
            /** Total Skills */
            total_skills: number;
            /** Progress */
            progress: number;
        };
        /**
         * CurrentUserOut
         * @description Identity plus everything the top stats bar needs, in one request.
         */
        CurrentUserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Avatar Color */
            avatar_color: string;
            /** Current Course Id */
            current_course_id: number | null;
            /** Total Xp */
            total_xp: number;
            /** Gems */
            gems: number;
            hearts: components["schemas"]["HeartsOut"];
            streak: components["schemas"]["StreakOut"];
            daily: components["schemas"]["DailyGoalOut"];
        };
        /** DailyGoalOut */
        DailyGoalOut: {
            /** Daily Xp */
            daily_xp: number;
            /** Daily Goal */
            daily_goal: number;
            /** Daily Goal Completed */
            daily_goal_completed: boolean;
        };
        /** DailyXpOut */
        DailyXpOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Xp */
            xp: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @example LESSON_LOCKED
             */
            code: string;
            /**
             * Message
             * @example This lesson is locked.
             */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** FillBlankAnswer */
        FillBlankAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fill_blank";
            /** Text */
            text: string;
        };
        /** FillBlankContent */
        FillBlankContent: {
            /**
             * Before
             * @default
             */
            before: string;
            /**
             * After
             * @default
             */
            after: string;
            /** Translation */
            translation?: string | null;
            /** Options */
            options?: string[] | null;
        };
        /** FillBlankExerciseOut */
        FillBlankExerciseOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fill_blank";
            content: components["schemas"]["FillBlankContent"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @constant
             */
            database: "ok";
        };
        /** HeartsOut */
        HeartsOut: {
            /** Current */
            current: number;
            /** Max */
            max: number;
            /**
             * Next Heart At
             * @description When the next heart regenerates; null if full.
             */
            next_heart_at: string | null;
            /** Regen Minutes */
            regen_minutes: number;
            /** Refill Cost Gems */
            refill_cost_gems: number;
        };
        /** LeaderboardOut */
        LeaderboardOut: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /**
             * Resets At
             * Format: date-time
             */
            resets_at: string;
            /** Entries */
            entries: components["schemas"]["LeaderboardRowOut"][];
            current_user: components["schemas"]["LeaderboardStandingOut"];
        };
        /** LeaderboardRowOut */
        LeaderboardRowOut: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: number;
            /** Display Name */
            display_name: string;
            /** Avatar Color */
            avatar_color: string;
            /** Xp */
            xp: number;
            /** Is Current User */
            is_current_user: boolean;
        };
        /** LeaderboardStandingOut */
        LeaderboardStandingOut: {
            /** Rank */
            rank: number;
            /** Xp */
            xp: number;
        };
        /**
         * LessonOut
         * @description Everything needed to render a lesson — and nothing that reveals an answer.
         */
        LessonOut: {
            /** Id */
            id: number;
            /** Skill Id */
            skill_id: number;
            /** Title */
            title: string | null;
            /** Xp Reward */
            xp_reward: number;
            /** Exercises */
            exercises: (components["schemas"]["MultipleChoiceExerciseOut"] | components["schemas"]["WordBankExerciseOut"] | components["schemas"]["MatchPairsExerciseOut"] | components["schemas"]["FillBlankExerciseOut"] | components["schemas"]["TypeAnswerExerciseOut"])[];
        };
        /**
         * LessonStatus
         * @enum {string}
         */
        LessonStatus: "locked" | "available" | "completed";
        /** MatchPairsAnswer */
        MatchPairsAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "match_pairs";
            /** Pairs */
            pairs: components["schemas"]["SubmittedPair"][];
        };
        /** MatchPairsContent */
        MatchPairsContent: {
            /** Left */
            left: components["schemas"]["PairItem"][];
            /** Right */
            right: components["schemas"]["PairItem"][];
        };
        /** MatchPairsExerciseOut */
        MatchPairsExerciseOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "match_pairs";
            content: components["schemas"]["MatchPairsContent"];
        };
        /** MultipleChoiceAnswer */
        MultipleChoiceAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multiple_choice";
            /** Option Id */
            option_id: string;
        };
        /** MultipleChoiceContent */
        MultipleChoiceContent: {
            /** Source Text */
            source_text?: string | null;
            /** Options */
            options: components["schemas"]["ChoiceOption"][];
        };
        /** MultipleChoiceExerciseOut */
        MultipleChoiceExerciseOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multiple_choice";
            content: components["schemas"]["MultipleChoiceContent"];
        };
        /** PairItem */
        PairItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** PathOut */
        PathOut: {
            course: components["schemas"]["CourseOut"];
            /** Current Skill Id */
            current_skill_id: number | null;
            /** Current Lesson Id */
            current_lesson_id: number | null;
            /** Units */
            units: components["schemas"]["PathUnitOut"][];
        };
        /** PathSkillOut */
        PathSkillOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Icon */
            icon: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["SkillStatus"];
            /** Lessons Completed */
            lessons_completed: number;
            /** Total Lessons */
            total_lessons: number;
            /** Progress */
            progress: number;
            /** Next Lesson Id */
            next_lesson_id: number | null;
        };
        /** PathUnitOut */
        PathUnitOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Theme */
            theme: string;
            /** Skills */
            skills: components["schemas"]["PathSkillOut"][];
        };
        /** ProfileAchievementOut */
        ProfileAchievementOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            metric: components["schemas"]["AchievementMetric"];
            /** Threshold */
            threshold: number;
            /** Progress */
            progress: number;
            /** Earned At */
            earned_at: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            user: components["schemas"]["ProfileUserOut"];
            stats: components["schemas"]["ProfileStatsOut"];
            /** Achievements */
            achievements: components["schemas"]["ProfileAchievementOut"][];
        };
        /** ProfileStatsOut */
        ProfileStatsOut: {
            /** Total Xp */
            total_xp: number;
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Lessons Completed */
            lessons_completed: number;
            /** Skills Completed */
            skills_completed: number;
            /** Weekly Xp */
            weekly_xp: number;
            /** League Rank */
            league_rank: number;
        };
        /** ProfileUserOut */
        ProfileUserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Avatar Color */
            avatar_color: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Total Xp */
            total_xp: number;
            daily: components["schemas"]["DailyGoalOut"];
            streak: components["schemas"]["StreakOut"];
            /** Lessons Completed */
            lessons_completed: number;
            /** Skills Completed */
            skills_completed: number;
            /** Courses */
            courses: components["schemas"]["CourseProgressOut"][];
            /** Last 7 Days */
            last_7_days: components["schemas"]["DailyXpOut"][];
        };
        /** RefillOut */
        RefillOut: {
            hearts: components["schemas"]["HeartsOut"];
            /** Gems */
            gems: number;
        };
        /** SkillDetailOut */
        SkillDetailOut: {
            /** Id */
            id: number;
            /** Unit Id */
            unit_id: number;
            /** Course Id */
            course_id: number;
            /** Title */
            title: string;
            /** Icon */
            icon: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["SkillStatus"];
            /** Lessons Completed */
            lessons_completed: number;
            /** Total Lessons */
            total_lessons: number;
            /** Progress */
            progress: number;
            /** Next Lesson Id */
            next_lesson_id: number | null;
            /** Lessons */
            lessons: components["schemas"]["SkillLessonOut"][];
        };
        /** SkillLessonOut */
        SkillLessonOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Title */
            title: string | null;
            /** Xp Reward */
            xp_reward: number;
            /** Exercise Count */
            exercise_count: number;
            status: components["schemas"]["LessonStatus"];
        };
        /** SkillProgressOut */
        SkillProgressOut: {
            /** Skill Id */
            skill_id: number;
            status: components["schemas"]["SkillStatus"];
            /** Lessons Completed */
            lessons_completed: number;
            /** Total Lessons */
            total_lessons: number;
            /** Progress */
            progress: number;
        };
        /**
         * SkillStatus
         * @enum {string}
         */
        SkillStatus: "locked" | "available" | "in_progress" | "completed";
        /** StreakOut */
        StreakOut: {
            /**
             * Current
             * @description Displayed streak (0 once a day has been missed).
             */
            current: number;
            /** Longest */
            longest: number;
            /**
             * Active Today
             * @description Whether a lesson was completed today.
             */
            active_today: boolean;
        };
        /** SubmittedPair */
        SubmittedPair: {
            /** Left Id */
            left_id: string;
            /** Right Id */
            right_id: string;
        };
        /** TypeAnswerAnswer */
        TypeAnswerAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "type_answer";
            /** Text */
            text: string;
        };
        /** TypeAnswerContent */
        TypeAnswerContent: {
            /** Source Text */
            source_text: string;
            /** Source Language */
            source_language: string;
            /** Target Language */
            target_language: string;
        };
        /** TypeAnswerExerciseOut */
        TypeAnswerExerciseOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "type_answer";
            content: components["schemas"]["TypeAnswerContent"];
        };
        /** UpdateUserIn */
        UpdateUserIn: {
            /**
             * Daily Goal Xp
             * @description Daily XP goal.
             * @enum {integer}
             */
            daily_goal_xp: 10 | 20 | 30 | 50;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WordBankAnswer */
        WordBankAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "word_bank";
            /** Tile Ids */
            tile_ids: string[];
        };
        /** WordBankContent */
        WordBankContent: {
            /** Source Text */
            source_text: string;
            /** Tiles */
            tiles: components["schemas"]["WordTile"][];
        };
        /** WordBankExerciseOut */
        WordBankExerciseOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "word_bank";
            content: components["schemas"]["WordBankContent"];
        };
        /** WordTile */
        WordTile: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** XpAwardOut */
        XpAwardOut: {
            source: components["schemas"]["XpSource"];
            /** Amount */
            amount: number;
        };
        /**
         * XpSource
         * @enum {string}
         */
        XpSource: "lesson_completion" | "perfect_bonus" | "seed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_me_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseListOut"];
                };
            };
        };
    };
    get_course_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetailOut"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_path_api_courses__course_id__path_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathOut"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_skill_api_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailOut"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_lesson_api_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Forbidden (e.g. LESSON_LOCKED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_attempt_api_lessons__lesson_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptOut"];
                };
            };
            /** @description Forbidden (e.g. LESSON_LOCKED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict with the current state (e.g. OUT_OF_HEARTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    check_answer_api_lessons__lesson_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAnswerOut"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict with the current state (e.g. OUT_OF_HEARTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_progress_api_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
        };
    };
    complete_lesson_api_progress_lesson__lesson_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteLessonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteLessonOut"];
                };
            };
            /** @description Forbidden (e.g. LESSON_LOCKED) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict with the current state (e.g. OUT_OF_HEARTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_hearts_api_hearts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartsOut"];
                };
            };
        };
    };
    refill_hearts_api_hearts_refill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefillOut"];
                };
            };
            /** @description Conflict with the current state (e.g. OUT_OF_HEARTS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request (VALIDATION_ERROR, INVALID_ANSWER) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_leaderboard_api_leaderboard_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
}
